### ISSUE TITLE
hjkl scrolling, for Vim addicts

### ISSUE THREAD

**Issue by daveyarwood** [orangeduck/imgcurses#3]
Allowing users to scroll left/down/up/right using the Vim `hjkl` key-bindings would be a nice feature.

I just stumbled upon this project today and am excited about it. I'd offer to do a Pull Request for this, but my C skills are sadly lacking at the moment. (I've just started reading your book, though, so hopefully that will change!)

**Comment by orangeduck** [comment]
Good idea. I'll look into at at some point (it is a simple change) but if you feel like tackling it at any point then go ahead. The code for managing the controls is near the bottom of `imgcurses.c`.

Thanks,
- Dan

**Comment by daveyarwood** [comment]
Actually, this looks pretty doable. I'll take a crack at it.
